version: '3.2'
services:
    app:
        image: golang:latest
        ports:
            - "8080:8080"
        container_name: ca_tech_dojo
        volumes:
            - ./:/go
        tty: true
        depends_on:
            - mysql
    mysql:
        ports: 
          - "3306:3306"
        image: mysql:5.7
        container_name: mysql-container
        build: ./
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ca_tech
          MYSQL_USER: ca_tech
          MYSQL_PASSWORD: ca_tech
        volumes:       
            - ./initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
        #   - ./db/mysql_data:/var/lib/mysql

    
